<script type="text/javascript">
    require(['jquery', 'domReady!'], function($){
        (function() {
            $('.action-delete').each(function() {
                var data_post = $(this).attr('data-post-action');
                if (data_post) {
                    $(this).attr('data-post', data_post);
                }
            });
        })($);
    });
</script>


<script type="text/javascript">
    require([
        'jquery',
        'mage/translate',
        'Magento_Ui/js/modal/confirm',
        "mage/template",
    ], function ($, $t, confirm, mageTemplate) {
        $('.action-delete').click(function (e) {
            e.stopPropagation();
            confirm({
                title: $t("Remove item cart"),
                content: $t("Do you want remove this item of the cart?"),
                modalClass: "classModal",
                actions: {
                    confirm: function () {
                        var params = $(e.currentTarget).data('post');
                        var formTemplate = '<form action="<%- data.action %>" method="post">'
                            + '<% _.each(data.data, function(value, index) { %>'
                            + '<input name="<%- index %>" value="<%- value %>">'
                            + '<% }) %></form>';

                        var formKeyInputSelector = 'input[name="form_key"]';

                        var formKey = $(formKeyInputSelector).val();
                        console.log(formKey);
                        if (formKey) {
                            params.data.form_key = formKey;
                        }
                        $(mageTemplate(formTemplate, {
                            data: params
                        })).appendTo('body').hide().submit();
                    }
                }
            });
            setTimeout(function () {
                $(".modal-popup.classModal._show").css("z-index", "1001");
                $(".modal-popup.classModal._show ~ .modal-popup.classModal._show").remove();
                $("aside.modal-popup.confirm._show").remove();
            }, 30);
        })
    });
</script>
