<?php
 /**  @var $block \Candela\Blog\Block\Adminhtml\System\Config\Field\Layout\Renderer */?>
<div class="mp-layout-element"
     mp-name="<?= $block->escapeHtml($block->getElementName()); ?>"
     mp-id="<?= $block->escapeHtml($block->getElementId()); ?>"
     mp-value='<?= $block->escapeHtml($block->getElementValue()) ?>'
     mp-config='<?= /* @noEscape */ $block->getLayoutConfigJson(); ?>'>
</div>
