<?php

/** @var \Candela\Blog\Block\Comments $block */

$collection = $block->getCollection();
?>

<div class="amblog-comments-livestream">
    <?php if ($collection && $collection->getSize()) : ?>
        <div class="amblog-amp-title -comment"><?= $block->escapeHtml(__('Comments')); ?></div>
        <?php foreach ($collection as $message) : ?>
            <?= $block->getMessageHtml($message); ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
