<?php

/** @var \Candela\Blog\Block\Content\Post\Details $block */

$tags = $block->getTags(); ?>

<?php if ($tags && count($tags)): ?>
    <?php $isFirst = true; ?>
    <?php foreach ($tags as $tag): ?>
        <?php if (!$isFirst): ?>
            ,
        <?php endif ?>
        <a href="<?= $block->escapeUrl($tag->getUrl()); ?>" class="amblog-tag">
            #<?= $block->escapeHtml($tag->getName()); ?>
        </a>
        <?php $isFirst = false; ?>
    <?php endforeach; ?>
<?php endif; ?>
