<?php

/**
 * @var \Candela\Blog\Block\Layout\WidgetWrapper $block
 * @var \Magento\Framework\Escaper $escaper
 */

$wrappedBlock = $block->getWrappedBlock();
?>

<?php if ($wrappedBlock): ?>
    <?php if ($result = trim($wrappedBlock->toHtml())): ?>
        <div data-amblog-js="element-block" class="desktop-block amblog-element-block"
             data-set="sidebar-<?= $escaper->escapeHtml($block->getWrappedBlockIdentifier()); ?>">
            <?= /** @noEscape */ $result ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
